### ISSUE TITLE
Old issue.. never dealt with.. reposted

### ISSUE THREAD

**Issue by mlawtk** [basak/csipsimple#1]
Reported by dco...@gmail.com, Dec 5, 2014
What steps will reproduce the problem?
1. Leave the phone to go into deep sleep
2. Call the phone 
3. Phone doesn't ring, voice mail pops up on the callee phone
4. After 20 seconds or never, until user manually wakes up phone, sipsimple starts ringing, but the call is long gone

What is the expected output? What do you see instead?

1. Wake up from deep sleep and ring

What version of the product are you using? On what device / operating
system?

Latest version from appstore.
LG-D805
OS 4.2.2

Please provide any additional information below.

csipsimple is simply useless if it cannot receive calls when the phone is on standby.

Jun 22, 2015 Project Member #1 r3gis...@gmail.com
(No comment was entered for this change.)
Status: Obsolete 
Jun 22, 2015 #2 dco...@gmail.com
Why is this obsolete, we still have the same problem. Phones that go to deep sleep never get the chance to receive a call through csipsimple.
Jun 22, 2015 Project Member #3 r3gis...@gmail.com

Currently migrating to github; Google closes googlecode.

**Comment by basak** [comment]
Sorry, this is just a personal mirror of a git conversion I did of the csipsimple VCS. I am not csipsimple upstream.
